### ISSUE TITLE
NPM start semantic-ui error 

### ISSUE THREAD

**Issue by kslr** [lordfriend/Deneb#46]
```shell
ERROR in ./~/semantic-ui-less/semantic.less
Module build failed: ModuleNotFoundError: Module not found: Error: Can't resolve './themes/themes/default/assets/fonts/icons.eot' in '/Users/kslr/Develop/Deneb/node_modules/semantic-ui-less'
    at factoryCallback (/Users/kslr/Develop/Deneb/node_modules/webpack/lib/Compilation.js:264:39)
    at factory (/Users/kslr/Develop/Deneb/node_modules/webpack/lib/NormalModuleFactory.js:247:20)
    at resolver (/Users/kslr/Develop/Deneb/node_modules/webpack/lib/NormalModuleFactory.js:65:21)
    at asyncLib.parallel.e (/Users/kslr/Develop/Deneb/node_modules/webpack/lib/NormalModuleFactory.js:138:21)
    at /Users/kslr/Develop/Deneb/node_modules/webpack/node_modules/async/dist/async.js:3838:9
    at /Users/kslr/Develop/Deneb/node_modules/webpack/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/kslr/Develop/Deneb/node_modules/webpack/node_modules/async/dist/async.js:996:13)
    at /Users/kslr/Develop/Deneb/node_modules/webpack/node_modules/async/dist/async.js:906:16
    at /Users/kslr/Develop/Deneb/node_modules/webpack/node_modules/async/dist/async.js:3835:13
    at resolvers.normal.resolve (/Users/kslr/Develop/Deneb/node_modules/webpack/lib/NormalModuleFactory.js:130:23)
    at onResolved (/Users/kslr/Develop/Deneb/node_modules/enhanced-resolve/lib/Resolver.js:70:11)
    at loggingCallbackWrapper (/Users/kslr/Develop/Deneb/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/kslr/Develop/Deneb/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/Users/kslr/Develop/Deneb/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/kslr/Develop/Deneb/node_modules/tapable/lib/Tapable.js:181:46)
    at innerCallback (/Users/kslr/Develop/Deneb/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
    at loggingCallbackWrapper (/Users/kslr/Develop/Deneb/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/kslr/Develop/Deneb/node_modules/tapable/lib/Tapable.js:283:15
    at /Users/kslr/Develop/Deneb/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:38:4
    at loggingCallbackWrapper (/Users/kslr/Develop/Deneb/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/kslr/Develop/Deneb/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/Users/kslr/Develop/Deneb/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
 @ ./src/ng2-semantic/index.ts 1:0-41
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi (webpack)-dev-server/client?http://0.0.0.0:3000 ./src/main.browser.ts

ERROR in ./~/semantic-ui-less/semantic.less
Module build failed: ModuleNotFoundError: Module not found: Error: Can't resolve './themes/themes/default/assets/fonts/icons.eot' in '/Users/kslr/Develop/Deneb/node_modules/semantic-ui-less'
    at factoryCallback (/Users/kslr/Develop/Deneb/node_modules/webpack/lib/Compilation.js:264:39)
    at factory (/Users/kslr/Develop/Deneb/node_modules/webpack/lib/NormalModuleFactory.js:247:20)
    at resolver (/Users/kslr/Develop/Deneb/node_modules/webpack/lib/NormalModuleFactory.js:65:21)
    at asyncLib.parallel.e (/Users/kslr/Develop/Deneb/node_modules/webpack/lib/NormalModuleFactory.js:138:21)
    at /Users/kslr/Develop/Deneb/node_modules/webpack/node_modules/async/dist/async.js:3838:9
    at /Users/kslr/Develop/Deneb/node_modules/webpack/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/kslr/Develop/Deneb/node_modules/webpack/node_modules/async/dist/async.js:996:13)
    at /Users/kslr/Develop/Deneb/node_modules/webpack/node_modules/async/dist/async.js:906:16
    at /Users/kslr/Develop/Deneb/node_modules/webpack/node_modules/async/dist/async.js:3835:13
    at resolvers.normal.resolve (/Users/kslr/Develop/Deneb/node_modules/webpack/lib/NormalModuleFactory.js:130:23)
    at onResolved (/Users/kslr/Develop/Deneb/node_modules/enhanced-resolve/lib/Resolver.js:70:11)
    at loggingCallbackWrapper (/Users/kslr/Develop/Deneb/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/kslr/Develop/Deneb/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/Users/kslr/Develop/Deneb/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/kslr/Develop/Deneb/node_modules/tapable/lib/Tapable.js:181:46)
    at innerCallback (/Users/kslr/Develop/Deneb/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
    at loggingCallbackWrapper (/Users/kslr/Develop/Deneb/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/kslr/Develop/Deneb/node_modules/tapable/lib/Tapable.js:283:15
    at /Users/kslr/Develop/Deneb/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:38:4
    at loggingCallbackWrapper (/Users/kslr/Develop/Deneb/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/kslr/Develop/Deneb/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/Users/kslr/Develop/Deneb/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)

ERROR in /Users/kslr/Develop/Deneb/node_modules/extract-text-webpack-plugin/loader.js??ref--3-0!/Users/kslr/Develop/Deneb/node_modules/style-loader/index.js!/Users/kslr/Develop/Deneb/node_modules/css-loader/index.js!/Users/kslr/Develop/Deneb/node_modules/semantic-ui-less-module-loader/index.js!/Users/kslr/Develop/Deneb/node_modules/semantic-ui-less/semantic.less doesn't export content
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 546 kB [entry] [rendered]
        [0] ./~/lodash/lodash.js 540 kB {0} [built]
            [] -> factory:1925ms building:1183ms = 3108ms
        [1] ./~/html-webpack-plugin/lib/loader.js!./src/index.html 5.58 kB {0} [built]
             factory:186ms building:103ms = 289ms
        [2] (webpack)/buildin/global.js 509 bytes {0} [built]
            [] -> factory:43ms building:29ms = 72ms
        [3] (webpack)/buildin/module.js 517 bytes {0} [built]
            [] -> factory:45ms building:29ms = 74ms
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 1.46 MB [entry] [rendered]
       [48] ./~/css-loader/lib/css-base.js 1.46 kB {0} [built]
            [] -> factory:6ms building:13ms = 19ms
       [49] ./~/semantic-ui-less/themes/default/assets/images/flags.png 95 bytes {0} [built]
            [] -> factory:22ms building:8ms = 30ms
       [50] ./~/css-loader!./~/semantic-ui-less-module-loader!./~/semantic-ui-less/semantic.less 1.46 MB {0} [built]
             factory:8ms dependencies:40ms building:27153ms = 27201ms
    
    ERROR in ./~/css-loader!./~/semantic-ui-less-module-loader!./~/semantic-ui-less/semantic.less
    Module not found: Error: Can't resolve './themes/themes/default/assets/fonts/icons.eot' in '/Users/kslr/Develop/Deneb/node_modules/semantic-ui-less'
     @ ./~/css-loader!./~/semantic-ui-less-module-loader!./~/semantic-ui-less/semantic.less 6:286161-286218 6:286241-286298
    
    ERROR in ./~/css-loader!./~/semantic-ui-less-module-loader!./~/semantic-ui-less/semantic.less
    Module not found: Error: Can't resolve './themes/themes/default/assets/fonts/icons.woff2' in '/Users/kslr/Develop/Deneb/node_modules/semantic-ui-less'
     @ ./~/css-loader!./~/semantic-ui-less-module-loader!./~/semantic-ui-less/semantic.less 6:286348-286407
    
    ERROR in ./~/css-loader!./~/semantic-ui-less-module-loader!./~/semantic-ui-less/semantic.less
    Module not found: Error: Can't resolve './themes/themes/default/assets/fonts/icons.woff' in '/Users/kslr/Develop/Deneb/node_modules/semantic-ui-less'
     @ ./~/css-loader!./~/semantic-ui-less-module-loader!./~/semantic-ui-less/semantic.less 6:286438-286496
    
    ERROR in ./~/css-loader!./~/semantic-ui-less-module-loader!./~/semantic-ui-less/semantic.less
    Module not found: Error: Can't resolve './themes/themes/default/assets/fonts/icons.ttf' in '/Users/kslr/Develop/Deneb/node_modules/semantic-ui-less'
     @ ./~/css-loader!./~/semantic-ui-less-module-loader!./~/semantic-ui-less/semantic.less 6:286526-286583
    
    ERROR in ./~/css-loader!./~/semantic-ui-less-module-loader!./~/semantic-ui-less/semantic.less
    Module not found: Error: Can't resolve './themes/themes/default/assets/fonts/icons.svg' in '/Users/kslr/Develop/Deneb/node_modules/semantic-ui-less'
     @ ./~/css-loader!./~/semantic-ui-less-module-loader!./~/semantic-ui-less/semantic.less 6:286617-286674
Child extract-text-webpack-plugin:
                                                Asset     Size  Chunks             Chunk Names
    images/flags.9c74e172f87984c48ddf5c8108cabe67.png  28.1 kB          [emitted]  
    chunk    {0} extract-text-webpack-plugin-output-filename 1.46 MB [entry]
       [48] ./~/css-loader/lib/css-base.js 1.46 kB {0} [built]
            [] -> factory:3ms building:5ms = 8ms
       [49] ./~/semantic-ui-less/themes/default/assets/images/flags.png 95 bytes {0} [built]
            [] -> factory:4ms building:4ms = 8ms
       [50] ./~/css-loader!./~/semantic-ui-less-module-loader!./~/semantic-ui-less/semantic.less 1.46 MB {0} [built]
             factory:1ms dependencies:555ms building:16841ms = 17397ms
    
    ERROR in ./~/css-loader!./~/semantic-ui-less-module-loader!./~/semantic-ui-less/semantic.less
    Module not found: Error: Can't resolve './themes/themes/default/assets/fonts/icons.eot' in '/Users/kslr/Develop/Deneb/node_modules/semantic-ui-less'
     @ ./~/css-loader!./~/semantic-ui-less-module-loader!./~/semantic-ui-less/semantic.less 6:286161-286218 6:286241-286298
    
    ERROR in ./~/css-loader!./~/semantic-ui-less-module-loader!./~/semantic-ui-less/semantic.less
    Module not found: Error: Can't resolve './themes/themes/default/assets/fonts/icons.woff2' in '/Users/kslr/Develop/Deneb/node_modules/semantic-ui-less'
     @ ./~/css-loader!./~/semantic-ui-less-module-loader!./~/semantic-ui-less/semantic.less 6:286348-286407
    
    ERROR in ./~/css-loader!./~/semantic-ui-less-module-loader!./~/semantic-ui-less/semantic.less
    Module not found: Error: Can't resolve './themes/themes/default/assets/fonts/icons.woff' in '/Users/kslr/Develop/Deneb/node_modules/semantic-ui-less'
     @ ./~/css-loader!./~/semantic-ui-less-module-loader!./~/semantic-ui-less/semantic.less 6:286438-286496
    
    ERROR in ./~/css-loader!./~/semantic-ui-less-module-loader!./~/semantic-ui-less/semantic.less
    Module not found: Error: Can't resolve './themes/themes/default/assets/fonts/icons.ttf' in '/Users/kslr/Develop/Deneb/node_modules/semantic-ui-less'
     @ ./~/css-loader!./~/semantic-ui-less-module-loader!./~/semantic-ui-less/semantic.less 6:286526-286583
    
    ERROR in ./~/css-loader!./~/semantic-ui-less-module-loader!./~/semantic-ui-less/semantic.less
    Module not found: Error: Can't resolve './themes/themes/default/assets/fonts/icons.svg' in '/Users/kslr/Develop/Deneb/node_modules/semantic-ui-less'
     @ ./~/css-loader!./~/semantic-ui-less-module-loader!./~/semantic-ui-less/semantic.less 6:286617-286674
webpack: Failed to compile.
```

It looks like the package lacks the font
I tried to copy the semantic-ui font under the assets, but failed

**Comment by lordfriend** [comment]
remove node_modules
try `yarn install` instead of `npm install`
then npm start

**Comment by lordfriend** [comment]
Additional Caution: I'm currently developing user-center feature at master branch (which is an accident). use with caution. some page may not work (like register, forget pass,). The user-center feature will soon merged into master at Albireo. after that, the master branch of this project will reach a stable state.

**Comment by kslr** [comment]
Yarn success, I will synchronize regularly and upstream.
But I did not find the location to add keywords, my level is 3.

**Comment by kslr** [comment]
Is it possible for locale to cause 400 errors?

server
```shell
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

client 
```shell
LANG="zh_CN.UTF-8"
LC_COLLATE="zh_CN.UTF-8"
LC_CTYPE="zh_CN.UTF-8"
LC_MESSAGES="zh_CN.UTF-8"
LC_MONETARY="zh_CN.UTF-8"
LC_NUMERIC="zh_CN.UTF-8"
LC_TIME="zh_CN.UTF-8"
LC_ALL=
```

server.py
![qq20170520-142341](https://cloud.githubusercontent.com/assets/5516323/26273706/f41ca30e-3d67-11e7-8afe-2d2840e339e4.png)

**Comment by lordfriend** [comment]
At home page, you can find `Management `,
![screenshot from 2017-05-20 14-21-37](https://cloud.githubusercontent.com/assets/1235614/26273707/f6341f8c-3d67-11e7-9822-5bb088485895.png)

**Comment by lordfriend** [comment]
It looks like that error cause by a different ip, maybe some other program try to access the server with some illegal request

**Comment by kslr** [comment]
You are right, I did not observe carefully, thank you for your help. :blush:
